import keyboard
print("Animes")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")
print("1.Attack on Titan")
print("2.Vinland Saga")
print("3.Demon Slayer")
print("Spirited Away")
print("One Piece")
print("Akira")
print("Death Note")
print("Princess Mononoke")
print("Porco Rosso")
print("Howl’s Moving Castle")
print("Steins;Gate")
print("Grave of The Fireflies")
print("Cowboy Bebop")
print("Fullmetal Alchemist: Brotherhood")
print("Dragon Ball Z")
print("Nausicaä of the Valley of the Wind")
print("The Cat Returns")
print("Neon Genesis Evangelion")
print("Mob Psycho 100")

print("Programdan çıkmak için Esc' ye basınız")

keyboard.wait("esc")

print("Programdan çıkıldı.")