print("Coutries")
print("")

print("Asian Countries")
print("Turkiye")
print("Georgia")
print("Ermenia")
print("Iraq")
print("Iran")
print("")

print("European Countries")
print("England")
print("Scotland")
print("Wales")
print("Northern Ireland")
print("Ireland")
print("Germany")
print("France")
print("")

print("South American")
print("Argentina")
print("Uruguay")
print("Brazil")