import keyboard

import colorama
from colorama import Fore, init
init()

print(Fore.BLUE,'Countries')
print("Coutries")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")
print(Fore.RED,'Asian Countries')
print("Asian Countries")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("Georgia")
print("Ermenia")
print("Iraq")
print("Iran")
print("China")
print("Japan")
print("Thailand")
print("South Korea")
print("Azerbaijan")
print("Bahrain")
print("Brunei")
print("Cambodia")
print("Cyprus")
print("Indonesia")
print("Israel")
print("Jordan")
print("Kuwait")
print("Kyrgyzstan")
print("Laos")
print("Lebanon")
print("Malaysia")
print("Maldives")
print("Nepal")
print("North Korea")
print("Pakistan")
print("Philippines")
print("Qatar")
print("Saudi Arabia")
print("Singapore")
print("Sri Lanka")
print("Taiwan")
print("Turkmenistan")
print("United Arab Emirates")
print("Uzbekistan")
print("Vietnam")
print("")

print("Devam etmek için entera basınız.")
keyboard.wait("enter")
print("")

print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")

print("European Countries")
print("")

print("Devam etmek için spacebara basınız.")
keyboard.wait("space")
print("")

print("United Kingdom")
print("Andorra")
print("Liechtenstein")
print("Austria") 
print("Iceland") 
print("Switzerland")
print("Ireland") 
print("Turkey")
print("Italy")
print("Luxembourg")
print("Germany") 
print("Spain") 
print("Malta")
print("Belgium")
print("Monaco")
print("Netherlands")
print("Poland")
print("Cyprus")
print("Portugal")
print("San-Marino")
print("France") 
print("")

print("Devam etmek için spacebara basınız.")
keyboard.wait("space")
print("")

print("Iskandinavian ve Baltik Countries")
print("")

print("Estonia") 
print("Russia")
print("Finland")
print("Denmark") 
print("Sweden")
print("Ukraine")
print("Latvia")
print("Lithuania")
print("Belarus") 
print("Norway")
print("")

print("Devam etmek için spacebara basınız.")
keyboard.wait("space")
print("")

print("Balkan Countries")
print("")

print("Devam etmek için spacebara basınız.")
keyboard.wait("space")
print("")

print("Bosnia Herzegovina") 
print("Montenegro")
print("Bulgaria") 
print("Croatia") 
print("Czech Republic")
print("Macedonia") 
print("Serbia")
print("Macedonia")
print("Moldova")
print("Slovakia")
print("Slovenia")
print("Greece") 
print("Romania")
print("Hungary") 
print("Kosovo")
print("Albania")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("South American Countries")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("Argentina")
print("Uruguay")
print("Brazil")
print("Paraguay")
print("Bolivia")
print("Chile") 
print("Colombia") 
print("Ecuador")
print("Guyana")
print("Peru") 
print("Suriname")
print("Venezuela")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("African Countries")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("Cezayir")
print("Angola")
print("Benin")
print("Botsvana")
print("Burkina Faso")
print("Burundi")
print("Cabo Verde")
print("Kamerun")
print("Orta Afrika Cumhuriyeti")
print("Çad")
print("Komorlar")
print("Kongo Demokratik Cumhuriyeti")
print("Kongo Cumhuriyeti")
print("Fildişi Sahili")
print("Cibuti")
print("Mısır")
print("Ekvator Ginesi")
print("Eritre")
print("Esvatini")
print("Etiyopya")
print("Gabon")
print("Gambiya")
print("Gana")
print("Gine")
print("Kenya")
print("Lesoto")
print("Liberya")
print("Libya")
print("Madagaskar")
print("Malawi")
print("Mali")
print("Moritanya")
print("Mauritius")
print("Fas")
print("Mozambik")
print("Namibya")
print("Nijer")
print("Nijerya")
print("Ruanda")
print("Senegal")
print("Seyşeller")
print("Sierra Leone")
print("Somali")
print("Güney Afrika")
print("Güney Sudan")
print("Sudan")
print("Tanzanya")
print("Tunus")
print("Uganda")
print("Zambiya")
print("Zimbabve")

print("Programdan çıkmak için Esc' ye basınız")

keyboard.wait("esc")

print("Programdan çıkıldı.")