import keyboard

import colorama
from colorama import Fore, init
init()

print(Fore.RED,'Countries')
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print(Fore.BLUE,'Asian Countries')
print("")

keyboard.wait("enter")
print(Fore.WHITE)
print("Georgia")
print("Ermenia")
print("Iraq")
print("Iran")
print("China")
print("Japan")
print("Thailand")
print("South Korea")
print("Azerbaijan")
print("Bahrain")
print("Brunei")
print("Cambodia")
print("Cyprus")
print("Indonesia")
print("Israel")
print("Jordan")
print("Kuwait")
print("Kyrgyzstan")
print("Laos")
print("Lebanon")
print("Malaysia")
print("Maldives")
print("Nepal")
print("North Korea")
print("Pakistan")
print("Philippines")
print("Qatar")
print("Saudi Arabia")
print("Singapore")
print("Sri Lanka")
print("Taiwan")
print("Turkmenistan")
print("United Arab Emirates")
print("Uzbekistan")
print("Vietnam")
print("")

keyboard.wait("enter")
print(Fore.GREEN,'European Countries')
print("")

keyboard.wait("enter")
print(Fore.WHITE)
print("United Kingdom")
print("Andorra")
print("Liechtenstein")
print("Austria") 
print("Iceland") 
print("Switzerland")
print("Ireland") 
print("Turkey")
print("Italy")
print("Luxembourg")
print("Germany") 
print("Spain") 
print("Malta")
print("Belgium")
print("Monaco")
print("Netherlands")
print("Poland")
print("Cyprus")
print("Portugal")
print("San-Marino")
print("France") 
print("")

keyboard.wait("enter")
print(Fore.YELLOW,'Iskandinavian ve Baltik Countries')
print("")

keyboard.wait("enter")
print(Fore.WHITE)
print("Estonia") 
print("Russia")
print("Finland")
print("Denmark") 
print("Sweden")
print("Ukraine")
print("Latvia")
print("Lithuania")
print("Belarus") 
print("Norway")
print("")

keyboard.wait("enter")
print(Fore.YELLOW, 'Balkan Countries')
print("")

keyboard.wait("enter")
print(Fore.WHITE)
print("Bosnia Herzegovina") 
print("Montenegro")
print("Bulgaria") 
print("Croatia") 
print("Czech Republic")
print("Macedonia") 
print("Serbia")
print("Macedonia")
print("Moldova")
print("Slovakia")
print("Slovenia")
print("Greece") 
print("Romania")
print("Hungary") 
print("Kosovo")
print("Albania")
print("")

keyboard.wait("enter")
print(Fore.RED, 'South American Countries')
print("")

keyboard.wait("enter")
print(Fore.WHITE)
print("Argentina")
print("Uruguay")
print("Brazil")
print("Paraguay")
print("Bolivia")
print("Chile") 
print("Colombia") 
print("Ecuador")
print("Guyana")
print("Peru") 
print("Suriname")
print("Venezuela")
print("")

keyboard.wait("enter")
print(Fore.RED, 'African Countries')
print("")

keyboard.wait("enter")
print(Fore.WHITE)
print("Cezayir")
print("Angola")
print("Benin")
print("Botsvana")
print("Burkina Faso")
print("Burundi")
print("Cabo Verde")
print("Kamerun")
print("Orta Afrika Cumhuriyeti")
print("Çad")
print("Komorlar")
print("Kongo Demokratik Cumhuriyeti")
print("Kongo Cumhuriyeti")
print("Fildişi Sahili")
print("Cibuti")
print("Mısır")
print("Ekvator Ginesi")
print("Eritre")
print("Esvatini")
print("Etiyopya")
print("Gabon")
print("Gambiya")
print("Gana")
print("Gine")
print("Kenya")
print("Lesoto")
print("Liberya")
print("Libya")
print("Madagaskar")
print("Malawi")
print("Mali")
print("Moritanya")
print("Mauritius")
print("Fas")
print("Mozambik")
print("Namibya")
print("Nijer")
print("Nijerya")
print("Ruanda")
print("Senegal")
print("Seyşeller")
print("Sierra Leone")
print("Somali")
print("Güney Afrika")
print("Güney Sudan")
print("Sudan")
print("Tanzanya")
print("Tunus")
print("Uganda")
print("Zambiya")
print("Zimbabve")

print("Programdan çıkmak için Esc' ye basınız")

keyboard.wait("esc")

print("Programdan çıkıldı.")