import keyboard
print("FootballClubs")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("German Football Clubs")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("Bayern München")
print("Borussia Dortmund") 
print("RB Leipzig")
print("Hamburg")
print("VfB Stuttgart")
print("1. FC_Köln")
print("Borussia Mönchengladbach")
print("Eintracht Frankfurt")
print("Werder Bremen") 
print("Bayer Leverkusen")
print("Augsburg")
print("VfL Bochum")
print("Eintracht Frankfurt")
print("Elversberg")
print("FC Heidenheim")
print("Freiburg")
print("Holstein Kiel")
print("Mainz 05")
print("St Pauli")
print("TSG Hoffenheim")
print("Union Berlin")
print("Vfl Wolfsburg")
print("Werder Bremen")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("Spanish Football Clubs")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("Real Madrid")
print("Atletico Madrid")
print("Alavés")
print("Almería")
print("Athletic Bilbao")
print("Barcelona")
print("Cádiz")
print("Celta Vigo")
print("Girona")
print("Espanyol")
print("Getafe")
print("Las Palmas")
print("Leganes")
print("Mallorca")
print("Osasuna")
print("Rayo Vallecano")
print("Real Betis")
print("Real Sociedad")
print("Sevilla")
print("Valencia")
print("Real Valladolid")
print("Villarreal")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("England Fottball Clubs")
print("Manchester United")
print("Arsenal")
print("Aston Villa")
print("AFC Bournemouth")
print("Brentford")
print("Brighton & Hove Albion")
print("Chelsea")
print("Crystal Palace")
print("Everton")
print("Fulham")
print("Ipswich Town")
print("Leicester City")
print("Liverpool")
print("Manchester City")
print("Newcastle United")
print("Nottingham Forest")
print("Southampton")
print("Tottenham Hotspur")
print("West Ham United")
print("Wolverhampton")


print("Programdan çıkmak için Esc' ye basınız")

keyboard.wait("esc")

print("Programdan çıkıldı.")