import keyboard
print("Tennis Players")
print("")

print("Devam etmek için space'a basiniz.")
keyboard.wait("space")

print("Men Tennis Players")
print("")
print("Novak Djokovic")
print("Boris Becker")
print("Björn Borg")
print("Taylor Dent")
print("Stefan Edberg")
print("Roger Federer")
print("Sébastien Grosjean")
print("Frank Hadow")
print("Rafael Nadal")
print("Patrick Rafter")
print("Marsel İlhan")
print("Andy Roddick")
print("Greg Rusedski")
print("Pete Sampras")
print("Bill Tilden")
print("Mats Wilander")
print("Pat Cash")
print("Henry Leconte")
print("Filippo Volandri")
print("Marcelo Rios")
print("Andy Murray")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")

print("Women Tennis Players")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")

print("Çağla Büyükakçay")
print("Mariya Şarapova")
print("Petra Kvitova")
print("Viktoriya Azarenka")
print("Sabine Appelmans")
print("Olga Barabanschikova")
print("Jennifer Capriati")
print("Kim Clijsters")
print("Amanda Coetzer")
print("Maureen Connolly")
print("Nadia Petrova")
print("Caroline Wozniacki")
print("Serena Williams")
print("Venus Williams")

print("Programdan çıkmak için Esc' ye basınız")

keyboard.wait("esc")

print("Programdan çıkıldı.")