import keyboard
print("Video Games")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")

print("1.Mobile Legends")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")

print("1. Tank Characters")
print("Fredrinn")
print("Edith")
print("Gloo")
print("Barats")
print("Atlas")
print("Baxia")
print("Khufra")
print("Belerick")
print("Uranus")
print("Hylos")
print("Grock")
print("Gatotkaca")
print("Johnson")
print("Minotaur")
print("Franco")
print("Akai")
print("Tigreal")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")

print("2. Assassins Characters")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")

print("Joy")
print("Aamon")
print("Benedetta")
print("Ling")
print("Hanzo")
print("Selena")
print("Gusion")
print("Helcurt")
print("Lancelot")
print("Natalia")
print("Hayabusa")
print("Fanny")
print("Karina")
print("Saber") 
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("MLBB e-spor teams and Regions")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print(" 1. Filipinler League-(MPL-PH)")
print("AP.Bren")
print("Team Liquid")
print("ONIC Philippines")
print("Smart Omega")
print("TNC Pro Team")
print("Aurora Gaming")
print("Twisted Minds")
print("Team Falcons")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print(" 2. Endonezya League-(MPL-ID)")
print("ONIC Esports")
print("RRQ Hoshi")
print("EVOS Legends")
print("Bigetron Alpha")
print("Alter Ego")
print("Geek Fam ID")
print("Aura Fire")
print("Rebellion Zion")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print(" 3. Turkiye League")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("Aurora")
print("Papara SuperMassive")
print("Fire Flux Esports")
print("S2G Esports")
print("Ulfhednar")
print("Fenerbahçe Esports")
print("FUT Esports")
print("Dark Passage")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("2.Legends of Legends")
print("")

print("1. LCK League-Güney Kore")
print("Gen.G")
print("Hanwha Life Esports")
print("T1")
print("Dplus KIA")
print("KT Rolster")
print("DRX")
print("Kwangdong Freecs")
print("Nongshim RedForce")
print("OKSavingsBank BRION")
print("BNK FearX")
print("")

print("3.Clash of Clans")
print("4.Boom Beach")
print("5.Minecraft")

print("Programdan çıkmak için Esc' ye basınız")

keyboard.wait("esc")

print("Programdan çıkıldı.")