import keyboard
print("Video Games")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")

print("1.Mobile Legends")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")

print("1. Tank Characters")
print("Fredrinn")
print("Edith")
print("Gloo")
print("Barats")
print("Atlas")
print("Baxia")
print("Khufra")
print("Belerick")
print("Uranus")
print("Hylos")
print("Grock")
print("Gatotkaca")
print("Johnson")
print("Minotaur")
print("Franco")
print("Akai")
print("Tigreal")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")

print("2. Assassins Characters")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")

print("Joy")
print("Aamon")
print("Benedetta")
print("Ling")
print("Hanzo")
print("Selena")
print("Gusion")
print("Helcurt")
print("Lancelot")
print("Natalia")
print("Hayabusa")
print("Fanny")
print("Karina")
print("Saber") 
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("MLBB e-spor teams and Regions")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print(" A. Filipinler League-(MPL-PH)")
print("AP.Bren")
print("Team Liquid")
print("ONIC Philippines")
print("Smart Omega")
print("TNC Pro Team")
print("Aurora Gaming")
print("Twisted Minds")
print("Team Falcons")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print(" B. Endonezya League-(MPL-ID)")
print("ONIC Esports")
print("RRQ Hoshi")
print("EVOS Legends")
print("Bigetron Alpha")
print("Alter Ego")
print("Geek Fam ID")
print("Aura Fire")
print("Rebellion Zion")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print(" C. Turkiye League")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("Aurora")
print("Papara SuperMassive")
print("Fire Flux Esports")
print("S2G Esports")
print("Ulfhednar")
print("Fenerbahçe Esports")
print("FUT Esports")
print("Dark Passage")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("D. Malezya (MPL-MY)")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("Selangor Red Giants")
print("HomeBois")
print("Team SMG")
print("Team HAQ")
print("TODAK")
print("Aero Esports")
print("DXSoul Esports")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")


print("E. Singapur (MPL-SG)")
print("")
print("RSG SG")
print("Team Flash")
print("NIP Flash")
print("Team Vamos")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("2.Legends of Legends")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("League of Legends Leagues") 
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("A. LCK League-South Korea")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("Gen.G")
print("Hanwha Life Esports")
print("T1")
print("Dplus KIA")
print("KT Rolster")
print("DRX")
print("Kwangdong Freecs")
print("Nongshim RedForce")
print("OKSavingsBank BRION")
print("BNK FearX")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("B. LPL League-China")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")      

print("Bilibili Gaming (BLG)")
print("Top Esports (TES)")
print("JD Gaming (JDG)")
print("EDward Gaming (EDG)")
print("Royal Never Give Up (RNG)")
print("LNG Esports")
print("FunPlus Phoenix (FPX)")
print("Invictus Gaming (IG)")
print("Weibo Gaming (WBG)")
print("Oh My God (OMG)")
print("Team WE (WE)")
print("Anyone's Legend (AL)")
print("Ninjas in Pyjamas (NIP)")
print("Ultra Prime (UP)")
print("TT Gaming (TT)")
print("LGD Gaming (LGD)")     
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("C. LEC-Avrupa")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("G2 Esports")
print("Fnatic")
print("Team Vitality")
print("Team BDS")
print("SK Gaming")
print("KOI")
print("MAD Lions")
print("Excel Esports")
print("Astralis")
print("Rogue")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")

print("D. VCS League-Vietnam Championship Series")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("GAM Esports")
print("Saigon Buffalo (SBTC Esports)")
print("Team Secret (Vietnam)")
print("Cerberus Esports")
print("Team Flash")
print("Burst the Sky")
print("Luxury Esports")
print("Percent Esports") 
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")

print("E. PCS-Pacific Championship Series")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("PSG Talon")
print("Beyond Gaming")
print("Machi Esports")
print("J Team")
print("Hong Kong Attitude")
print("Impunity Esports")
print("BOOM Esports")
print("Alpha Esports")
print("Liyab Esports")
print("Berjaya Dragons")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("F. LLA-Liga Latinoamérica")
print("")

print("Devam etmek için spacebar'a basiniz.")
keyboard.wait("space")
print("")

print("Infinity Esports")
print("Estral Esports")
print("Furious Gaming")
print("All Knights")
print("Isurus")
print("Rainbow7")
print("Kaos Latin Gamers")
print("XTEN Esports")
print("")

print("Devam etmek için enter'a basiniz.")
keyboard.wait("enter")
print("")

print("G. CBLOL-Campeonato Brasileiro de LoL")
print("")
print("LOUD")
print("PaiN Gaming")
print("RED Canids Kalunga")
print("FURIA")
print("Flamengo Esports")
print("INTZ")
print("Vivo Keyd")
print("KaBuM Esports")
print("Cruzeiro Esports")
print("Rensga Esports")

print("Programdan çıkmak için Esc' ye basınız")

keyboard.wait("esc")

print("Programdan çıkıldı.")